config/routes.rb
Rails.application.routes.draw do
  # get 'activity/index'
root :to => 'activities#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  resources :activities do
    collection do
  get :update

end
    end
  end

app/models/activity.rb
class Activity < ApplicationRecord
  has_and_belongs_to_many :members


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  has_and_belongs_to_many :activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_activity, only: [:show, :edit, :update, :destroy]


  def index
    @activities = Activity.all

    respond_to do |format|
      format.html {  }
      format.json {
        render :json => @activities
      }
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @activity.members
    respond_to do |format|
      format.html
      format.json {
        render :json => @activity.to_json(:include => :members)
      }
    end

  end

  def datosModal
    activity = Activity.find(params[:id])
    render :json => {:activity => activity}

  end

  def new
    @activity = Activity.new
    @a = Activity.find_by_id(params[:id])
    @activity_id = params[:activity_id]
  end

  def edit
  end

  def create
    @activity = Activity.new
    @activity.name = params[:name]
    @activity.description = params[:description]
    @activity.enddate = params[:enddate]

      if @activity.save
        render json: {done: true}
      else
        render json: {done: false}
      end
  end

  def update
    @activity_id = params[:activity_id]

    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'La actividad ha sido actualizada.' }
        format.json { render :json => @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'La actividad ha sido eliminada.' }
      format.json { head :no_content }
    end
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :description, :enddate, member_ids: [])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
<!--CONTENEDOR PRINCIPAL-->
<div id="activities" class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-12">
      <form id="formActivities">
        <input type="hidden" value="<%= activities_path %>" id="activityCreate">
        <div class="form-group" >
          <label>Nombre</label>
          <input type="text" class="form-control" id="activityName" placeholder="Nombre de la actividad"/>
        </div><br>
      </form>
      <ul id="listActivities" class="list-group">
        <% @activities.each do |activity| %>
        <li class="list-group-item" activity_id="<%= activity.id %>"><%= activity.name + ' '%> <%= link_to 'Eliminar', activity, method: :delete, data: { confirm: 'Está seguro?' }, class: 'btn btn-danger' %></li>
          <% end %>
      </ul>
    </div>
  </div>
</div>
<!--FIN CONTENEDOR PRINCIPAL-->
<!--INICIA MODAL-->

<div class="modal hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Detalles de la actividad</h4>
      </div>
      <div class="modal-body">
        <form id="formActivities">
          <input type="hidden" name="id" id="id_activity">
          <div class="form-group">
            <label>Nombre de la actividad</label>
            <input type="text" class="form-control" id="activityNameModal">
          </div>
          <div class="form-group">
            <label>Descripción</label>
            <input type="text" class="form-control" id="activityDescription">
          </div>
          <div class="form-group">
            <label>Término de la actividad</label>
            <input type="date" class="form-control" id="activityEndDate">
          </div>
          <div class="form-group">
            <label>Miembros designados</label>
            <% Member.all.each do |member| %>
              <label>
                <input name="activityMembers" type="checkbox" class="memberCheckbox_<%= member.id %> memberCheckboxCleaner " id="activityMember_<%= member.id %>" value="<%= member.id %>">
                <span><%= member.name%> </span>
              </label>
            <% end %>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" type="submit" id="updateActivity" data-dismiss="modal">Guardar</button>
      </div>
    </div>
  </div>
</div>
<!--FIN MODAL-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>